
name: RandomSpawns
main: Trxgically\RandomSpawns\Main
api: 3.0.0
version: 0.1
author: Trxgically
commands:
 randomspawns:
  description: "RandomSpawns default command"
  permission: randomspawns.perms
